import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./nav/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{/* Metadata and other head elements go here */}</head>
      <body className={inter.className}>
        {/* NavBar should be inside the body */}
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
