export const data = [
  {
    name: "Emma",
    username: "@emmamemma69",
    rating: "1.5",
    messages: [
      {
        type: "text",
        text: "speak again",
        sender: "me",
        date: "2024-09-25T03:25:17.478Z",
      },
      {
        type: "notification",
        text: "Updated a swap",
        sender: "other",
        date: "2024-09-25T03:25:25.926Z",
      },
      {
        type: "text",
        text: "what did u say",
        sender: "me",
        date: "2024-09-25T03:25:22.004Z",
      },
      {
        type: "text",
        text: "nothing...",
        sender: "other",
        date: "2024-09-25T03:25:25.926Z",
      },
    ],
    lastMessage: "Hey there! How's it going? Just checking in.",
    date: "2023-09-19T12:30:00Z",
    viewed: false,
  },
  {
    name: "Siarra",
    username: "@siarrakachow",
    rating: "4.5",
    messages: [],
    lastMessage: "",
    date: "2024-09-18T09:15:00Z",
    viewed: true,
  },
  {
    name: "Allan",
    username: "@allanpoo",
    rating: "4",
    messages: [],
    lastMessage: "I found the information you requested about the project.",
    date: "2024-09-17T14:00:00Z",
    viewed: false,
  },
  {
    name: "Warren",
    username: "@yukisfather",
    rating: "3.5",
    messages: [],
    lastMessage: "Can you send me the updated report when you have a moment?",
    date: "2024-09-16T08:45:00Z",
    viewed: true,
  },
  {
    name: "Aaron",
    username: "@turtgussy",
    rating: "0",
    messages: [],
    lastMessage: "Looking forward to our weekend trip!",
    date: "2024-09-15T18:00:00Z",
    viewed: false,
  },
  {
    name: "Adeline",
    username: "@addyisverysaddy",
    rating: "5",
    messages: [],
    lastMessage: "Can you send me the updated report when you have a moment?",
    date: "2024-09-16T08:45:00Z",
    viewed: true,
  },
];
